#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace


#xcode-select --install
#/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install golang