name: CI

on: [push,pull_request,workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [ '1.16']

    runs-on: ${{ matrix.os }}

    steps:
      - name: step1
        run: bash -c "pwd;  ls -la"
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          submodules: true
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      # - if: matrix.os == 'macos-latest'
      #   run: |
      #     make install
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo make install
      # - if: matrix.os == 'windows-latest'
      #   run: |
      #     make install
      - name: build
        run: make build
      - name: self-test
        run: make self-test